// فصل 33 از کتاب — تبدیل‌شده از نسخهٔ HTML؛ ویرایش دستی لازم نیست.
// Chapter 33 of the book — converted from the HTML edition; generated file.

export const n = 33;
export const num = "33";
export const title = "۳۰ نکته و ترفند طلایی Git و GitHub";
export const label = "فصل ۳۳ · ۳۰ نکته طلایی";
export const part = 3;
export const html = "<p class=\"lead\">سی نکتهٔ کوتاه برای کار روزانه. هر مورد یک عادت است؛ لازم نیست همه را یک‌روزه حفظ کنی.</p>\n  <h2><span class=\"hx\"><span class=\"hx-t\">🎯 اهداف یادگیری</span></span></h2>\n<ul>\n<li>سی عادت را در کار روزانه بشناسی</li>\n<li>بدانی کدام ترفند تاریخچه را بازنویسی می‌کند</li>\n</ul>\n<h2><span class=\"hx\"><span class=\"hx-t\">⌨️ ترمینال</span></span></h2>\n<ol>\n<li><code>git switch -</code> برگشت به شاخهٔ قبلی.</li>\n<li><code>git log -1 --format='%H'</code> هش کامل HEAD.</li>\n<li><code>git show HEAD:src/app.ts</code> فایل را از کامیت بخوان بدون checkout.</li>\n<li><code>git add -p</code> جراحی hunk.</li>\n<li><code>git commit --fixup</code> + <code>rebase --autosquash</code>.</li>\n<li><code>git pull --ff-only</code> یا هیچ.</li>\n<li><code>git push --force-with-lease</code> نه <code>--force</code>.</li>\n<li><code>git fetch --prune</code> شاخهٔ مرده را پاک می‌کند.</li>\n<li><code>alias.lg</code> گراف رنگی.</li>\n<li><code>git config --global help.autocorrect 10</code> فرمان نزدیک را اجرا می‌کند.</li>\n</ol>\n<h2><span class=\"hx\"><span class=\"hx-t\">🖥️ VS Code</span></span></h2>\n<ol start=\"11\">\n<li><code>Ctrl+Shift+G</code> عضلهٔ اصلی.</li>\n<li>Stage Selected Ranges به‌جای کل فایل.</li>\n<li>Timeline قبل از panic.</li>\n<li><code>git.autofetch</code> روشن، Sync آگاهانه.</li>\n<li><code>git.branchProtection</code> روی <code>main</code>.</li>\n<li>PR را داخل ادیتور Checkout کن.</li>\n<li>Merge Editor سه‌ستونه برای تعارض سخت.</li>\n<li><code>code --wait</code> به‌عنوان editor گیت.</li>\n<li>Worktree + پنجرهٔ جدید برای هات‌فیکس.</li>\n<li>Git Output را بخوان؛ UI خطا را قورت می‌دهد.</li>\n</ol>\n<h2><span class=\"hx\"><span class=\"hx-t\">🐙 GitHub</span></span></h2>\n<ol start=\"21\">\n<li>PR زیر ۴۰۰ خط.</li>\n<li><code>Fixes #id</code> در بدنه.</li>\n<li>Draft تا CI سبز.</li>\n<li>Squash یا merge commit — یکی برای کل تیم.</li>\n<li>CODEOWNERS + Ruleset.</li>\n<li><code>gh pr checks</code> قبل از ping کردن ریویوکننده.</li>\n<li>Dependabot را ignore نکن؛ زمان‌بندی کن.</li>\n<li>Release Immutable.</li>\n<li><code>gh alias</code> برای کارهای تکراری.</li>\n<li>README فارسی با <code>dir=&quot;rtl&quot;</code> شرم ندارد.</li>\n</ol>\n<div class=\"callout callout-tip\"><div class=\"callout-title\">کارت یادآوری Undo</div>\n<p>Working → <code>restore</code> · Index → <code>restore --staged</code> · کامیت محلی → <code>reset --soft</code> · عمومی → <code>revert</code> · گمشده → <code>reflog</code></p>\n</div>\n<div class=\"callout callout-interview\"><div class=\"callout-title\">سؤالات مصاحبه (با پاسخ)</div>\n<p><strong>هر سطح:</strong> یکی از این سی تا را در مصاحبه به‌عنوان عادت روزانه‌ات تعریف کن — بهتر از حفظ flag.</p>\n</div>\n<h2><span class=\"hx\"><span class=\"hx-t\">✅ جمع‌بندی</span></span></h2>\n<p>نکته بدون مدل ذهنی شعبده است. اگر فصل ۳ را بلدی، این سی تا ارزان‌اند.</p>\n<p><strong>فصل بعد:</strong> کارگاه عملی چهار مینی‌پروژه.</p>";
export default { n, num, title, label, part, html };
